name: Deploy to vz.hccs.dev GitHub Pages
on:
  push: { branches: [main] }
  workflow_dispatch:
jobs:
  ghp:
    name: Build/Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm i
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
